name: Bug report
description: Report a bug you encountered
title: 'bug: '
labels:
  - bug
body:
  - type: checkboxes
    id: '1'
    attributes:
      label: Checklist
      description: Please follow the general troubleshooting steps first
      options:
        - label: >-
            I have checked open and closed [issues](https://github.com/Viren070/AIOStreams/issues)
          required: true
  - type: dropdown
    id: '9'
    attributes:
      label: Deployment Method
      description: Enter how you are using the addon
      options:
        - Public ElfHosted Instance
        - Private ElfHosted Instance
        - Other, specify at description
    validations:
      required: true
  - type: input
    id: '10'
    attributes:
      label: Addon Version
      description: What version of the addon were you using. If you were using Hugging Face, Render, or Cloudflare Workers, which commit did you build off, or around what time did you deploy
      placeholder: v1.7.4
    validations:
      required: true
  - type: dropdown
    id: '3'
    attributes:
      label: Bug Area
      description: Select what area of the addon this issue affects
      options:
        - Build Proces
        - Configuring the addon
        - Using the addon
    validations:
      required: true
  - type: input
    id: '2'
    attributes: 
      label: Device/Browser/OS/Stremio Version
      description: Details about the device this issue occurs on. Leave blank if not applicable (e.g. error within addon)
      placeholder: Windows on Stremio 5 Beta
  - type: textarea
    id: '4'
    attributes:
      label: Bug Description / Steps to Reproduce
      description: Precisely describe the bug you encountered and the steps to reproduce it. Avoid vague descriptions.
    validations:
      required: true
  - type: textarea
    id: '5'
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.
  - type: textarea
    id: '6'
    attributes:
      label: Screenshots
      description: If applicable, add screenshots of the bug. Include screenshots of your configuration if applicable.
  - type: checkboxes
    id: '8'
    attributes:
      label: Debugging Checklist
      description: Confirm you have included at least some of the following debugging information. If you haven't, please do so before submitting the issue.
      options:
        - label: >-
            If applicable, I have included server logs 
          required: false
        - label: >-
            If applicable, I have included MediaFlow logs
          required: false

